apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongodb
  namespace: suraj
  labels:
    tier: db
    env: dev
    project: suraj

spec:
  selector:
    matchLabels:
      tier: db
      env: dev
      project: suraj
  serviceName: mongodb
  replicas: 3
  template:
    metadata:
      labels:
        tier: db
        env: dev
        project: suraj
    spec:
      containers:
      - name: mongodb
        image: 296062550816.dkr.ecr.us-east-1.amazonaws.com/suraj/dev/mongodb:latest
        args:
        - /bin/sh
        - -c
        - touch suraj.txt
        livenessProbe:
          exec:
            command:
              - cat
              - suraj.txt
          initialDelaySeconds: 5
          periodSeconds: 10
        imagePullPolicy: Always
        resources:
          requests:
            memory: "500Mi"
            cpu: "500m"
          limits:
            memory: "1000Mi"
            cpu: "1000m"
        volumeMounts:
        - name: mongodb
          mountPath: /data/db
  volumeClaimTemplates:
  - metadata:
      name: mongodb
    spec:
      accessModes: ["ReadWriteOnce"]
      storageClassName: "ebs-sc"
      resources:
        requests:
          storage: 5Gi

---

apiVersion: v1
kind: Service
metadata:
  name: mongodb
  namespace: suraj

spec:
  clusterIP: None
  selector:
    tier: db
    env: dev
    project: suraj

  ports:
  - name: mongodb-port
    protocol: TCP
    port: 27017
    targetPort: 27017